// Shared tooltip copy so every page explains a derived metric the same way.
export const HINTS = {
  mark: "Mark price — the exchange's fair price used for PnL and liquidation (index + funding basis). Falls back to the last trade.",
  index: "Index price — volume-weighted spot price across major exchanges.",
  funding: "Funding rate for the current 8 h interval; longs pay shorts when positive. Countdown to the next mark (00:00 / 08:00 / 16:00 UTC).",
  liq: "Liquidation price — where the margin (notional / leverage) is exhausted: long entry × (1 − 1/lev + 0.5 %), short entry × (1 + 1/lev − 0.5 %). Spot-like positions (leverage 1) cannot be liquidated.",
  roe: "Return on equity — unrealized PnL / margin. With leverage this is PnL % × leverage.",
  pnl: "Unrealized PnL at mark, before the exit fee.",
  mae: "Maximum adverse excursion — the worst unrealized drawdown of the position since entry, in basis points of notional.",
  mfe: "Maximum favourable excursion — the best unrealized gain since entry, in basis points of notional.",
  margin: "Margin — capital reserved for the position: notional / leverage.",
  notional: "Notional — size × mark price.",
  hold: "Time since the position was opened (live clock).",
  sl: "Stop-loss level and its distance from mark. Empty when the strategy manages exits itself (trend daily).",
  tp: "Take-profit level and its distance from mark.",
  fees: "Fees paid so far (entry fee, plus funding when applicable).",
  trigger: "The condition that fired the entry (e.g. donchian_ensemble, zscore_entry, structure_break).",
  spread: "Best ask − best bid, in basis points of mid.",
  oi: "Open interest — total outstanding contracts on the venue (from the market snapshot).",
  vol24: "24 h quote volume on the venue (USD).",
  change24: "Change vs the open 24 h ago, from the 1m candles kept in memory.",
  regime: "Market regime detected on the 15m frame (ranging / trending / breakout) and how long it has held.",
  slippage: "Realised slippage of the entry fill vs the expected price, in basis points.",
  bps: "Round-trip return in basis points of the entry notional (net of fees).",
  exitReason: "Why the position closed: stop-loss, take-profit, strategy signal, max hold time, daily rebalance, trend exit or manual close.",
  equityAfter: "Account equity right after this trade closed.",
  available: "Available balance — equity minus margin used by open positions.",
  marginRatio: "Margin used / equity. The closer to 100 %, the closer the account is to liquidation.",
  exposure: "Position value / equity.",
  levEff: "Effective leverage — total position value / equity.",
  drawdown: "Distance from the all-time equity peak.",
  dailyPnl: "Realised PnL since 00:00 UTC (the daily loss limit resets then).",
  weeklyPnl: "Realised PnL since Monday 00:00 UTC.",
  feesToday: "Trading fees paid since 00:00 UTC.",
  strength: "Signal strength 0–1 as reported by the strategy (confidence / score).",
} as const;
