// Shared tooltip copy so every page explains a derived metric the same way.
export const HINTS = {
  mark: "Mark price — the exchange's fair price used for PnL and liquidation (index + funding basis). Falls back to the last trade.",
  index: "Index price — volume-weighted spot price across major exchanges.",
  funding: "Funding rate for the venue's current settlement (Strike settles hourly). Positive = long pays short, so this long-only book PAYS; negative = short pays long, so it IS PAID. Coloured by sign, like the venue. Countdown to the next settlement.",
  liq: "Liquidation price — where the margin (notional / leverage) is exhausted: long entry × (1 − 1/lev + 0.5 %), short entry × (1 + 1/lev − 0.5 %). Spot-like positions (leverage 1) cannot be liquidated.",
  roe: "Return on equity — unrealized PnL / margin. With leverage this is PnL % × leverage.",
  pnl: "Unrealized PnL at mark, before the exit fee.",
  mae: "Maximum adverse excursion — the deepest the market went AGAINST this position since it opened, in basis points of the entry price. It is the heat the position took before the outcome; MAE close to your stop means the stop is barely surviving.",
  mfe: "Maximum favourable excursion — the furthest the market went IN FAVOUR since the position opened, in basis points of the entry price. Compared with the PNL you actually keep, it says how much of a winner the exits gave back. On the daily trend book both are measured on daily bars.",
  margin: "Margin — capital reserved for the position: notional / leverage.",
  notional: "Notional — size × mark price.",
  hold: "Time since the position was opened (live clock).",
  sl: "Stop-loss level and its distance from mark. Empty when the strategy manages exits itself (trend daily).",
  tp: "Take-profit level and its distance from mark.",
  fees: "Entry fee of this position, debited at the fill (a position opened before 5 Sep 2026 pays it at the close). Funding has its own column.",
  fundingPaid: "Perpetual funding accrued on this position since it opened. Negative = the book paid; positive = it was received.",
  fundingTotal: "Every funding settlement the account has paid or received since the bot started, across all markets. Already included in realised PNL.",
  exitLadder: "This position exits in steps. Each Donchian lookback has its own trailing stop that never falls; when price closes below one, that share leaves. There is no take profit: trend returns come from letting winners run.",
  exitLegs: "Sub-strategies of the Donchian ensemble still holding, out of the total — how committed the position still is.",
  trigger: "The condition that fired the entry (e.g. donchian_ensemble, zscore_entry, structure_break).",
  spread: "Best ask − best bid, in basis points of mid.",
  oi: "Open interest on the VENUE — total outstanding contracts on Strike, not on the price feed. Four of Strike's markets carry none, and zero there is a fact, not a missing value.",
  range24: "Highest and lowest of the last 24 hours. Strike publishes these as TRADED extremes, so on a market that trades a few times a day the mark can sit outside them — the live mark is folded in here so the range always contains the current price.",
  vol24: "24 h quote volume on the VENUE (USD), as Strike publishes it. Not the price feed's: Strike turned over $1.9 M of BTC on the day Binance did $16 bn, and only the first figure says anything about the book an order reaches.",
  change24: "The venue's own 24 h change field. Strike's web front-end anchors its 24 h window a little differently and reads a few tenths apart from Strike's own API — this shows the API's figure, which is the one everything else here is computed from.",
  regime: "Market regime detected on the 15m frame (ranging / trending / breakout) and how long it has held.",
  slippage: "Realised slippage of the entry fill vs the expected price, in basis points.",
  bps: "Round-trip return in basis points of the entry notional (net of fees).",
  exitReason: "Why the position closed: stop-loss, take-profit, strategy signal, max hold time, daily rebalance, trend exit or manual close.",
  equityAfter: "Account equity right after this trade closed.",
  available: "Available balance — equity minus margin used by open positions.",
  marginRatio: "Margin used / equity. The closer to 100 %, the closer the account is to liquidation.",
  exposure: "Position value / equity.",
  levEff: "Effective leverage — total position value / equity.",
  drawdown: "Distance from the all-time equity peak.",
  dailyPnl: "PnL since 00:00 UTC, mark-to-market: closed trades and funding plus how the open positions moved. The daily loss limit is measured on this.",
  weeklyPnl: "PnL since Monday 00:00 UTC, mark-to-market (closed trades, funding and the open positions' move).",
  feesToday: "Trading fees paid since 00:00 UTC.",
  strength: "Signal strength 0–1 as reported by the strategy (confidence / score).",
} as const;
